### ISSUE TITLE
unclear dll referencing in Coupled MetaSWAP - Modflow6 model example

### ISSUE THREAD

**Issue by Manangka** [Deltares/iMOD-Documentation#24]
In GitLab by @tvw11 on Nov 1, 2023, 10:44

By providing a few necessary paths to the modflow and metaswap libraries for iMOD Coupler, we can write the coupled models. You can download the modflow and metaswap libraries as part of the `the last iMOD5 release <https://oss.deltares.nl/web/imod/download-imod5>`_

    mf6_dll = "./path/to/mf6.dll"
    metaswap_dll = "./path/to/metaswap.dll"
    metaswap_dll_dependency = "./path/to/metaswap/dll/dependency"

Downloading via the link went fine, but afterwards it is unclear which paths should be inserted here, especially the metaswap_dll_dependency, which should be the dir (probably renaming to metaswap_coupler_dir could already make it more clear).

**Comment by JoerivanEngelen** [comment]
Transferred this issue to the iMOD-Documentation repository, as MetaMod is moved to the ``primod`` package (part of the iMOD Coupler project). The example has now become part of the generic iMOD-Documentation. We still need to resolve https://github.com/Deltares/imod-python/issues/672 to reduce confusion, because there is still a lot of redundancy here.
